### ISSUE TITLE
[Feature] SageMaker MLOPs Modules

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#144]
**Is your feature request related to a problem? Please describe.**
As a customer, I'd like to leverage the full capabilities of SageMaker for ML training for different models. To do this, I need to deploy a development environment for ML (SageMaker Studio), custom kernels for use during model development, custom images for use with SageMaker Processing & SageMaker Training jobs. 

Finally, I need the ability to scale ML solutions for multiple model training pipelines and for this we should leverage SageMaker Projects, which needs a custom Module that allows designing and deploying custom organizational templates. 

**Describe the solution you'd like**
Add support for a SageMaker native MLOPs solution including:
- Module to Deploy SageMaker Studio
- Module to Deploy a Custom SageMaker Project
- Module to Build, Deploy and Register Custom Kernels for Studio

**Comment by dgraeber** [comment]
20220227 - Status of PR:
The PR has been rejected due to the following:

- the code does not deploy due to circular dependencies of sagemaker-studio and custom-kernel definitions 
- the README of new modules are incomplete
- alignment of output of new modules vs README are not aligned


This PR does not deploy end-to-end with the code submitted.

**Comment by dgraeber** [comment]
I corrected the above issues

**Comment by dgraeber** [comment]
https://github.com/awslabs/autonomous-driving-data-framework/pull/165
