### ISSUE TITLE
[BUG] Replace EMR-Launch from stack

### ISSUE THREAD

**Issue by dgraeber** [awslabs/autonomous-driving-data-framework#349]
With the new emr-serverless module in IDF-modules, using emr-launch (from pypi) should be re-evaluated.

- Remove emr-launch dependency from `rosbag-scene-detection` module
- search all modules for emr-launch and remove

**Comment by srinivasreddych** [comment]
IMO, its not worth refactoring RSD module w/ EMR Serverless because we have made a decision to deprecate that module already and updated in the [README](https://github.com/awslabs/autonomous-driving-data-framework/tree/main/modules/analysis/rosbag-scene-detection#introduction).

AFAIK, RSD is the only module which uses emr launch.
