### ISSUE TITLE
[BUG] Misleading word in Module Manifest section

### ISSUE THREAD

**Issue by forszpanen** [awslabs/autonomous-driving-data-framework#390]
**Describe the bug**
I'm getting famillair with seedfarmer and I'm not sure if it's a bug or done on purpose but I think if "the name of the group" could be changed into "the name of the module". It would be helpful to underestand what this name means exactly. If I'm wrong just please add more context to this section in documentation.

**To Reproduce**
https://github.com/awslabs/seed-farmer/blob/54eac1d433c2e2f7eefafb055229814382eb2146/docs/source/manifests.md?plain=1#L247

**Expected behavior**
the name of the module

**Comment by dgraeber** [comment]
@forszpanen you are correct...that is a typo and I will remediate.  It should say "the name of the module".

What the name represents is a logical or physical name.  In other words, you can reuse the same module code in the same manifest, but each instance of the module MUST have a unique name in order to be valid.

I will leave this issue open so you can review, but will implement the update in the[ seedfarmer repository.](https://github.com/awslabs/seed-farmer)
Thanks!

**Comment by dgraeber** [comment]
This has been addressed in https://github.com/awslabs/seed-farmer/pull/468
